### ISSUE TITLE
Задание 1

### ISSUE THREAD

**Issue by readysloth** [kdator/arch_vs#1]
Как думаете, как компилятор оптимизировал бы это место?)
(Подсказка: битовые сдвиги)
![image](https://user-images.githubusercontent.com/28711485/97480066-fc488580-1963-11eb-8411-78675be41f9f.png)

**Comment by Shok1r** [comment]
Скорее всего он разложит одно из чисел на степени двойки например пусть в dx лежит 5, получится 3 * 5 = 11 * 101 = 11 * (1 * 2^2 + 1 * 2^0) = 11 * 2^2 + 11, где 11*2^2 можно представить как сдвиг влево на 2 бита, ну и потом прибавляем оставшееся (если и там будет множитель двойки, то это сдвиг влево на количество битов равных степеней двойки), то есть все сведется к сумме

**Comment by kdator** [comment]
![_IvlWf0nw80](https://user-images.githubusercontent.com/48220756/97484033-44b67200-1969-11eb-9f37-c6a4156783a1.jpg)

практика подсказывает, что компилятору всё равно на команды умножения и так далее. он просто начинает всё складывать.

**Comment by kdator** [comment]
![Uploading 5MKvlvwx9_M.jpg…]()

**Comment by kdator** [comment]
![5MKvlvwx9_M](https://user-images.githubusercontent.com/48220756/97484355-b42c6180-1969-11eb-80f1-21eee19c12e8.jpg)

**Comment by Shok1r** [comment]
Когда одно из чисел является степенью двойки он использует sall сдвиг влево на степень двойки

**Comment by Shok1r** [comment]
Или когда число можно привести к степени двойки, потестил 13 * 5, компилятор разделил на 13 * 4 + 13
![image](https://user-images.githubusercontent.com/60868809/97484918-711ebe00-196a-11eb-8fb6-7963f67530ea.png)

**Comment by Shok1r** [comment]
А вот при 23 * 7 следующее
![image](https://user-images.githubusercontent.com/60868809/97485106-bc38d100-196a-11eb-83cc-9d96282301bc.png)
