### ISSUE TITLE
Вопросы к лабораторной №4 

### ISSUE THREAD

**Issue by readysloth** [kdator/arch_vs#2]
+ Есть несколько способов поставить программную точку останова в C/C++ коде (аналогичную `pdb.set_trace()` в питоне). Как это будет записано с помощью ассемблерной вставки?
+ Каким образом (назовите хотя бы один) можно принудительно выставить флаги процессора в те значения, которые вы хотите

Ну и просто интересная ссылочка :)
https://habr.com/ru/post/520920/

**Comment by Shok1r** [comment]
1) По поводу точек останова, написано в статье https://habr.com/ru/post/103073/
Конкретно, достаточно вставить __asm { int 3;}  или  __asm { db 0xCC;}
2) По поводу выставления флагов - http://osinavi.ru/asm/5.html , есть специальные команды, которые позволяют манипулировать ими
